# Generated by Django 5.2.11 on 2026-05-04 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=80, unique=True, verbose_name='URL-фрагмент')),
                ('tagline', models.CharField(blank=True, max_length=220, verbose_name='Короткий слоган')),
                ('description', models.TextField(blank=True, verbose_name='О мероприятии')),
                ('format', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('hybrid', 'Гибрид')], default='online', max_length=16, verbose_name='Формат')),
                ('venue', models.CharField(blank=True, max_length=255, verbose_name='Площадка / город')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Анонс'), ('registration', 'Регистрация'), ('ongoing', 'Идёт хакатон'), ('finished', 'Завершён')], default='draft', max_length=20, verbose_name='Статус')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True, verbose_name='Регистрация с')),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True, verbose_name='Регистрация до')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Старт хакинга')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн сдачи / демо')),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. команд')),
                ('tracks', models.TextField(blank=True, help_text='Каждая строка — отдельный трек: FinTech, EdTech, …', verbose_name='Направления (треки)')),
                ('prizes', models.TextField(blank=True, verbose_name='Призы и номинации')),
                ('rules', models.TextField(blank=True, verbose_name='Правила и требования к проектам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hackathons', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Хакатон',
                'verbose_name_plural': 'Хакатоны',
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HackathonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=120, verbose_name='Название команды')),
                ('looking_for_team', models.BooleanField(default=False, verbose_name='Ищу команду')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий для организаторов')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='hackathons.hackathon', verbose_name='Хакатон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Регистрация на хакатон',
                'verbose_name_plural': 'Регистрации на хакатоны',
                'unique_together': {('user', 'hackathon')},
            },
        ),
    ]
