# Generated by Django 5.2.11 on 2026-05-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_hackathon_results_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Например, 15.', null=True, verbose_name='Возраст до'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Например, 11.', null=True, verbose_name='Возраст от'),
        ),
    ]
