# Generated by Django 5.2.11 on 2026-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_hackathon_max_age_hackathon_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='audience',
            field=models.CharField(choices=[('open', 'Открыто для всех'), ('school_7_11', 'Школьники 7-11 класс'), ('students', 'Студенты'), ('mixed', 'Смешанные команды'), ('professionals', 'Профессионалы')], default='open', max_length=20, verbose_name='Целевая аудитория'),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='level',
            field=models.CharField(choices=[('any', 'Любой'), ('starter', 'Стартер'), ('product', 'Продуктовый'), ('pro', 'Профи')], default='any', max_length=20, verbose_name='Уровень сложности'),
        ),
    ]
