# Generated by Django 5.2.11 on 2026-05-07 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_hackathon_audience_hackathon_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(db_index=True, max_length=120, verbose_name='Команда')),
                ('channel', models.CharField(choices=[('team', 'Внутри команды'), ('organizer', 'Команда и организатор')], default='team', max_length=20, verbose_name='Канал')),
                ('body', models.TextField(max_length=2000, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Отправлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='hackathons.hackathon', verbose_name='Хакатон')),
            ],
            options={
                'verbose_name': 'Сообщение чата хакатона',
                'verbose_name_plural': 'Чат хакатона',
                'ordering': ['created_at'],
            },
        ),
    ]
