# Generated by Django 5.2.11 on 2026-05-07 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0005_hackathonchatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название команды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_hackathon_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капитан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hackathon_teams', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='hackathons.hackathon', verbose_name='Хакатон')),
            ],
            options={
                'verbose_name': 'Команда хакатона',
                'verbose_name_plural': 'Команды хакатона',
                'ordering': ['name', 'pk'],
                'unique_together': {('hackathon', 'name')},
            },
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='hackathons.hackathonteam', verbose_name='Команда'),
        ),
    ]
