# Generated by Django 5.2.11 on 2026-05-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_hackathon_team_member_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonVideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('team', 'Внутрикомандный зал'), ('org', 'Команда и организатор')], max_length=16, verbose_name='Канал')),
                ('meeting_id', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='ID встречи BBB')),
                ('moderator_pw', models.CharField(max_length=64, verbose_name='Пароль модератора')),
                ('attendee_pw', models.CharField(max_length=64, verbose_name='Пароль участника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_rooms', to='hackathons.hackathon', verbose_name='Хакатон')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_rooms', to='hackathons.hackathonteam', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Видеокомната (BBB)',
                'verbose_name_plural': 'Видеокомнаты (BBB)',
                'constraints': [models.UniqueConstraint(fields=('hackathon', 'team', 'channel'), name='hackathons_videoroom_hackathon_team_channel_uq')],
            },
        ),
    ]
