# Generated by Django 5.2.11 on 2026-02-15 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Условие задачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='Максимальный балл')),
                ('expected_output', models.TextField(blank=True, verbose_name='Эталонный ответ (для проверки)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='competitions.competition', verbose_name='Соревнование')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['competition', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Код / ответ')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Зачтено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='competitions.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='competitions.competition', verbose_name='Соревнование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участие',
                'verbose_name_plural': 'Участия',
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
