# Generated by Django 5.2.11 on 2026-05-05 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_task_matching_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='auto_partial_enabled',
            field=models.BooleanField(default=True, help_text='Если выключено, для этого типа задач автопроверка работает по схеме 0 / max.', verbose_name='Частичная автооценка включена'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='partial_weight_percent',
            field=models.PositiveSmallIntegerField(default=100, help_text='Применяется к результату автопроверки: 100 = без изменений, 80 = 80% от балла.', verbose_name='Вес типа в автооценке, %'),
        ),
        migrations.CreateModel(
            name='SolutionGradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='Статус до')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='Статус после')),
                ('from_score', models.IntegerField(default=0, verbose_name='Баллы до')),
                ('to_score', models.IntegerField(default=0, verbose_name='Баллы после')),
                ('from_comment', models.TextField(blank=True, verbose_name='Комментарий до')),
                ('to_comment', models.TextField(blank=True, verbose_name='Комментарий после')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Причина / заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_grade_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_events', to='competitions.solution', verbose_name='Решение')),
            ],
            options={
                'verbose_name': 'Событие оценивания',
                'verbose_name_plural': 'История оценивания',
                'ordering': ['-created_at'],
            },
        ),
    ]
