# Generated by Django 5.2.11 on 2026-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_competition_max_age_competition_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='audience',
            field=models.CharField(choices=[('open', 'Открыто для всех'), ('school_5_8', 'Школьники 5-8 класс'), ('school_9_11', 'Школьники 9-11 класс'), ('students', 'Студенты'), ('teachers', 'Педагоги')], default='open', max_length=20, verbose_name='Целевая аудитория'),
        ),
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[('any', 'Любой'), ('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='any', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='competition',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Если пусто — без лимита.', null=True, verbose_name='Лимит участников'),
        ),
    ]
