# Generated by Django 5.2.11 on 2026-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_competition_audience_competition_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='attachment',
            field=models.FileField(blank=True, help_text='Опционально: архив проекта, скриншот, презентация и т.п.', null=True, upload_to='solutions/%Y/%m/', verbose_name='Файл решения'),
        ),
        migrations.AddField(
            model_name='task',
            name='organizer_material',
            field=models.FileField(blank=True, help_text='Можно приложить PDF/архив/документ с примерами или данными.', null=True, upload_to='competition_materials/%Y/%m/', verbose_name='Материал от организатора'),
        ),
    ]
